In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/train.csv') #Download the dataset from kaggle

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
len(df.columns)

12

In [ ]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
df[['Age']]

      Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

Handling Missing/Null Values

In [ ]:
df['Age'].isnull().sum()

np.int64(177)

In [ ]:
df['Age'] = df['Age'].fillna(int(df['Age'].mean()))

In [ ]:
df['Age'].isnull().sum()

np.int64(0)

In [ ]:
df.drop('Name', axis=1, inplace=True)

In [ ]:
len(df.columns)

11

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
df.drop('Cabin', axis=1, inplace=True)

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.560236,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.005010,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
def fun(value):
    if value<18:
        return 'child'
    else:
        return 'adult'

df['age_description'] = df['Age'].apply(fun)

In [ ]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,age_description
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,S,adult
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C,adult
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,adult
3,4,1,1,female,35.0,1,0,113803,53.1000,S,adult
4,5,0,3,male,35.0,0,0,373450,8.0500,S,adult
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,S,adult
887,888,1,1,female,19.0,0,0,112053,30.0000,S,adult
888,889,0,3,female,29.0,1,2,W./C. 6607,23.4500,S,adult
889,890,1,1,male,26.0,0,0,111369,30.0000,C,adult
890,891,0,3,male,32.0,0,0,370376,7.7500,Q,adult

Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

In [ ]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,age_description
0,1,0,3,1,22.0,1,0,A/5 21171,7.2500,S,adult
1,2,1,1,0,38.0,1,0,PC 17599,71.2833,C,adult
2,3,1,3,0,26.0,0,0,STON/O2. 3101282,7.9250,S,adult
3,4,1,1,0,35.0,1,0,113803,53.1000,S,adult
4,5,0,3,1,35.0,0,0,373450,8.0500,S,adult
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.0,0,0,211536,13.0000,S,adult
887,888,1,1,0,19.0,0,0,112053,30.0000,S,adult
888,889,0,3,0,29.0,1,2,W./C. 6607,23.4500,S,adult
889,890,1,1,1,26.0,0,0,111369,30.0000,C,adult
890,891,0,3,1,32.0,0,0,370376,7.7500,Q,adult

In [ ]:
ohe = OneHotEncoder()

In [ ]:
encoded = ohe.fit_transform(df[['age_description']])

In [ ]:
ohe.get_feature_names_out()

array(['age_description_adult', 'age_description_child'], dtype=object)

In [ ]:
df_new = pd.DataFrame(encoded.toarray(), columns=ohe.get_feature_names_out())

In [ ]:
df_new

     age_description_adult  age_description_child
0                      1.0                    0.0
1                      1.0                    0.0
2                      1.0                    0.0
3                      1.0                    0.0
4                      1.0                    0.0
..                     ...                    ...
886                    1.0                    0.0
887                    1.0                    0.0
888                    1.0                    0.0
889                    1.0                    0.0
890                    1.0                    0.0

[891 rows x 2 columns]